/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.*/

import java.util.Scanner;

public class Find_the_Difference {
    public char findTheDifference(String s, String t) 
    {
       String a = "2";
	   char b = (char)-2;
       char[] temp1 = (s+a).toCharArray();
       char[] temp2 = t.toCharArray();
       int i;
       loop: for(i=0;i<temp2.length;i++)
       {
           int j=0;
           for(j=0;j<temp2.length;j++)
             if(temp1[i]==temp2[j])
                {
                    temp2[j]= 49;
                    continue loop;
                }
       }
		for(i=0;i<temp2.length;i++)
            if(temp2[i]!=49)
                return temp2[i];    
    
        return b;
    }
	public static void main(String[] args)
	{
		Scanner sc = new Scanner(System.in);
		Find_the_Difference sol = new Find_the_Difference();
		String a,b;
		a = sc.nextLine();
		b = sc.nextLine();
		char ab;
		ab = sol.findTheDifference(a,b);
		System.out.println(ab);
	}

}
